Auth modal
the-monkeys/the_monkeys pull request #141
Opened 2024-03-03 18:14 UTC by Procax

2024-03-03 18:45 UTC, piyusharmap requested changes
In the last PR I have set up the monkey's logo outside the modal container cause it's looking a bit cluttered inside the modal. Keep it outside the modal container, everything else looks good.

2024-03-04 16:39 UTC, piyusharmap approved these changes

2024-03-04 17:28 UTC, daveaugustus approved these changes

2024-03-04 17:37 UTC, Rahullokare approved these changes

2024-03-04 17:39 UTC, merged