Add All tab and Collab tab
the-monkeys/the_monkeys pull request #175
Opened 2024-06-13 20:35 UTC by obere4u

### 📃 Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

**Related Tickets & Documents**

Fixes # (issue)

**What type of PR is this? (check all applicable)**

- [ ] 💡 Feature
- [ ] 🐛 Bug Fix
- [ ] 📃 Documentation Update
- [x] 🎨 Style Changes
- [ ] 💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test

### 🔰 Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### ❓ How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### 🔰 Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-14 07:21 UTC, piyusharmap requested changes
Fix the alignment of links in footer section.

2024-06-14 07:21 UTC, piyusharmap commented on src/components/layout/footer/index.tsx
> -      <div className='pb-8 space-y-2'>
Please don't alter the existing styling, as it affects the layout of the website. With the styling you have added, the footer links are moved to the left and are not properly visible on smaller screens.

2024-06-14 08:23 UTC, obere4u commented on src/components/layout/footer/index.tsx
> -      <div className='pb-8 space-y-2'>
Alright, that wasn't intentional though. I have fixed it

Let me push the code

2024-06-15 05:23 UTC, Rahullokare approved these changes

2024-06-15 05:24 UTC, merged